FROM debian:bookworm-slim AS build

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

ENV UV_PYTHON_INSTALL_DIR=/usr/local \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

RUN uv python install 3.14t

WORKDIR /app
RUN uv pip install --system Flask requests gunicorn

COPY . .

FROM debian:bookworm-slim

COPY --from=build /usr/local /usr/local
COPY --from=build /app /app
WORKDIR /app


CMD python3.14t -m gunicorn --worker-class gthread \
  --workers $WORKERS \
  --threads $ASYNC_CORES \
  --bind 0.0.0.0:$PORT_APP \
  app:app
